poll/models.py
from datetime import datetime

from flask_login import UserMixin

from poll.extensions import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True, nullable=False)
    email = db.Column(db.String, unique=True, nullable=False)
    password_hash = db.Column(db.String, nullable=False)
    registration_date = db.Column(db.DateTime, nullable=False, default=datetime.now())
    confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmation_date = db.Column(db.DateTime, nullable=True)
    votes = db.relationship('PollVote', backref='user', lazy='dynamic')
    polls = db.relationship('Poll', backref='creator')

    def __init__(self, username, email, password_hash):
        self.username = username
        self.email = email
        self.password_hash = password_hash

    def get_voted_polls(self):
        """

        Returns: the polls that the user has voted on

        """
        voted_poll_ids = [vote.poll_option.poll_id for vote in self.votes]
        return Poll.query.filter(Poll.id.in_(voted_poll_ids)).all()

    def voted_on(self, poll_id):
        """

        Args:
            poll_id: the id of the poll

        Returns: whether the user has voted on the poll with the id poll_id

        """
        for vote in self.votes:
            if vote.poll_option.poll.id == poll_id:
                return True
        return False


class Poll(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    multiple = db.Column(db.Boolean, default=False)
    created = db.Column(db.DateTime, default=datetime.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=True)
    options = db.relationship('PollOption', backref='poll', lazy=True)
    title = db.relationship('PollTitle', backref='poll', uselist=False)

    @staticmethod
    def get_most_popular(n):
        polls = Poll.query.all()
        polls.sort(reverse=True, key=Poll.get_vote_count)
        return polls[:n]

    @staticmethod
    def get_most_recent(n):
        polls = Poll.query.all()
        polls.sort(reverse=True, key=lambda x: x.created)
        return polls[:n]

    def get_vote_count(self):
        return sum(map(lambda x: x.get_vote_count(), self.options))

    def get_votes_of(self, user):
        votes = filter(lambda x: x.has_voted_on(user), self.options)
        return votes


class PollTitle(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    poll_id = db.Column(db.Integer, db.ForeignKey('poll.id'), nullable=False)
    text = db.Column(db.String(64), nullable=False)


class PollOption(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    poll_id = db.Column(db.Integer, db.ForeignKey('poll.id'), nullable=False)
    text = db.Column(db.String(64), nullable=False)
    votes = db.relationship('PollVote', backref='poll_option', lazy=True)

    def get_vote_count(self):
        return len(self.votes)

    def has_voted_on(self, user):
        for vote in self.votes:
            if vote.user_id == user.id:
                return True
        return False


class PollVote(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    poll_option_id = db.Column(db.Integer, db.ForeignKey('poll_option.id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

poll/poll/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, FieldList, SubmitField,  StringField
from wtforms.validators import DataRequired, ValidationError


class AtLeast:
    def __init__(self, min_=2, message=None):
        if not message:
            message = 'There should be at least 2 valid options.'
        self.message = message
        self.min = min_

    def __call__(self, form, field):
        options = map(lambda x: x.data, field.entries)
        options = list(filter(lambda x: x.strip(), options))

        if len(options) < self.min:
            raise ValidationError(self.message)


class CreatePollForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(message='Title is required.')])
    answer_options = FieldList(StringField(''), min_entries=2, label='Answer options', validators=[AtLeast()])
    multiple_choices = BooleanField('Multiple choices')
    submit = SubmitField('Create poll')

poll/__init__.py
import os

from flask import Flask
from flask_wtf.csrf import CSRFProtect

from poll import auth, main, poll, user
from poll.extensions import db, login_manager, migrate, mail
from poll.models import User


def create_app(config='config.DevConfig'):
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(config)

    login_manager.login_view = 'auth.login'
    login_manager.login_message_category = 'warning'
    login_manager.init_app(app)

    csrf = CSRFProtect()
    csrf.init_app(app)

    db.init_app(app)
    migrate.init_app(app, db)
    mail.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    app.register_blueprint(auth.bp)
    app.register_blueprint(main.bp)
    app.register_blueprint(poll.bp)
    app.register_blueprint(user.bp)

    return app

poll/auth.py
from datetime import datetime

from flask import Blueprint, redirect, render_template, url_for, flash, request, abort
from flask_login import login_required, login_user, logout_user, current_user
from flask_wtf import FlaskForm
from werkzeug.security import generate_password_hash, check_password_hash
from wtforms import StringField, PasswordField, SubmitField, EmailField
from wtforms.validators import Length, EqualTo, DataRequired, Email

from poll.email import send_email
from poll.model import db
from poll.models import User
from poll.safe_redirect import get_redirect_target, is_safe_url
from poll.token import generate_confirmation_token, confirm_token


class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=8)])
    confirm_password = PasswordField('Confirm password', validators=[EqualTo('password')])
    submit = SubmitField('Register')


class LoginForm(FlaskForm):
    username = StringField('Username')
    password = PasswordField('Password')
    submit = SubmitField('Login')


bp = Blueprint('auth', __name__)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    # POST
    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password = form.password.data

        user = User(username, email, generate_password_hash(password))

        db.session.add(user)
        db.session.commit()

        token = generate_confirmation_token(user.email)
        confirm_url = url_for('auth.confirm_email', token=token, _external=True)
        html = render_template('auth/activate.html', confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)

        return redirect(url_for('auth.login'))
    # GET
    return render_template('auth/register.html', form=form)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    next_ = request.args.get('next')
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        next_url = request.form.get('next')

        user = User.query.filter_by(username=username).first()
        if user is None or not check_password_hash(user.password_hash, password):
            # TODO: mark errors
            return redirect(url_for('auth.login'))

        login_user(user)

        if not is_safe_url(next_url):
            print("nem safe")
            abort(400)

        return redirect(next_url or url_for('main.index'))

    return render_template('auth/login.html', form=form, next=next_)


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@bp.route('/confirm/<token>')
@login_required
def confirm_email(token):
    email = confirm_token(token)
    if not email:
        flash('The confirmation link is invalid or has expired.', 'danger')
        return redirect(url_for('main.index'))
    user = User.query.filter_by(email=email).first_or_404()
    if user.id != current_user.id:
        flash('Wrong account')
        return redirect(url_for('main.index'))
    if user.confirmed:
        flash('Account already confirmed. Please login.', 'success')
    else:
        user.confirmed = True
        user.confirmation_date = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')
    return redirect(url_for('main.index'))

poll/main/__init__.py
from flask import Blueprint

from poll.main import views

bp = Blueprint(
    'main',
    __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/main/static'
)

bp.add_url_rule('/', view_func=views.index)

poll/main/views.py
from flask import render_template

from poll.models import Poll


def index():
    most_popular_polls = Poll.get_most_popular(5)
    most_recent_polls = Poll.get_most_recent(5)

    context = {
        'most_popular_polls': most_popular_polls,
        'most_recent_polls': most_recent_polls
    }

    return render_template('main/index.html', **context)

poll/poll/__init__.py
from flask import Blueprint

from poll.poll import views

bp = Blueprint(
    'poll',
    __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/poll/static'
)

bp.add_url_rule('/poll', view_func=views.poll)
bp.add_url_rule('/poll/<int:id_>', view_func=views.get_poll)
bp.add_url_rule('/poll/<int:id_>/result', view_func=views.get_poll_result)
bp.add_url_rule('/poll/<int:id_>', view_func=views.vote_poll, methods=['POST'])
bp.add_url_rule('/poll/create', view_func=views.create_poll, methods=['GET', 'POST'])

poll/poll/views.py
from flask import render_template, request, url_for, flash, current_app
from flask_login import login_required, current_user
from werkzeug.utils import redirect

from poll.extensions import db
from poll.models import PollVote, PollTitle, Poll
from poll.poll.forms import CreatePollForm
from poll.utils import poll_exists, custom_login_message, add_poll


def poll():
    return redirect(url_for('poll.create_poll'))


@custom_login_message(message='You have to log in to vote')
@login_required
def vote_poll(id_):
    if current_user.voted_on(id_):
        flash('You have already voted on this poll', 'error')
        return redirect(url_for('poll.get_poll', id_=id_))

    choices = request.form.getlist('choice')
    if choices:
        if (not Poll.query.get(id_).multiple) and len(choices) > 1:
            flash('Multiple choices are not allowed on this poll', 'error')
        else:
            for choice in choices:
                db.session.add(PollVote(poll_option_id=choice, user_id=current_user.id))
            db.session.commit()
            flash('You have successfully voted on this poll', 'success')

        return redirect(url_for('poll.get_poll', id_=id_))
    flash('You have to select at least one option', 'error')

    return redirect(url_for('poll.get_poll', id_=id_))


def get_poll(id_):
    if not poll_exists(id_):
        return redirect(url_for('main.index'))

    poll_ = Poll.query.get(id_)
    title = PollTitle.query.filter_by(poll_id=id_).first().text
    options = poll_.options
    multiple = poll_.multiple

    if current_user.is_authenticated and current_user.voted_on(id_):
        if request.referrer != url_for('poll.get_poll', id_=id_, _external=True):
            flash('You have already voted on this poll', 'info')

    context = {
        'poll_id': id_,
        'title': title,
        'options': options,
        'multiple': multiple
    }

    return render_template('poll/poll.html', **context)


def get_poll_result(id_):
    poll_ = Poll.query.get(id_)

    return render_template('poll/poll_result.html', poll=poll_)


def create_poll():
    form = CreatePollForm()
    if form.validate_on_submit():
        title = form.title.data
        options = form.answer_options.data
        multiple = form.multiple_choices.data

        options = filter(lambda x: x.strip(), options)
        id_ = add_poll(current_app, title, options, multiple)

        return redirect(url_for('poll.get_poll', id_=id_))

    return render_template('poll/create_poll.html', form=form)

poll/user/__init__.py
from flask import Blueprint

from poll.user import views

bp = Blueprint(
    'user',
    __name__,
    template_folder='templates',
    static_folder='static',
    url_prefix='/user'
)

bp.add_url_rule('/voted-polls', view_func=views.voted_polls)
bp.add_url_rule('/my-polls', view_func=views.my_polls)

poll/user/views.py
from flask import render_template
from flask_login import current_user, login_required


@login_required
def voted_polls():
    polls = current_user.get_voted_polls()
    return render_template('user/voted_polls.html', polls=polls)


@login_required
def my_polls():
    polls = current_user.polls
    return render_template('user/my_polls.html', polls=polls)

poll/templates/base.html
<!doctype html>
<html lang="en">
<head>
  {%- block head -%}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {%- block links -%}
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="stylesheet" href="{{ url_for('static', filename='style/base.css') }}">
  {%- endblock links %}
  <title>{% block title -%}{%- endblock -%}</title>
  {%- endblock head -%}
</head>
<body>
  {%- block body -%}
  <header>
    {% block header -%}
    <nav>
      <h1><a href="{{ url_for('main.index') }}">Poll</a></h1>
      {% if current_user.is_authenticated -%}
      <div class="dropdown" id="user-menu">
        <button id="user-btn" class="dropbtn">
          <span class="material-icons">account_circle</span>
        </button>
        <div id="user-dropdown" class="dropdown-content">
          <span><a href="{{ url_for('user.my_polls') }}">My polls</a></span>
          <span><a href="{{ url_for('user.voted_polls') }}">Voted polls</a></span>
          <span><a href="{{ url_for('auth.logout') }}">Log out</a></span>
        </div>
      </div>
      {%- else -%}
      <ul>
        <li>
          <div class="auth blue-bg" id="register">
            <a href="{{ url_for('auth.register') }}">Register</a>
          </div>
        </li>
        <li>
          <div class="auth blue-bg" id="login">
            <a href="{{ url_for('auth.login') }}">Log in</a>
          </div>
        </li>
      </ul>
      {%- endif %}
    </nav>
    {%- endblock %}
  </header>
  <div id="flash-messages">
  {%- with messages = get_flashed_messages(with_categories=True) %}
    {% if messages -%}
    <ul class="flash-messages">
      {%- for category, message in messages %}
      <li class="flash-message {{ category }}">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <span class="text">{{ message }}</span>
      </li>
      {%- endfor %}
    </ul>
    {%- endif %}
  {% endwith -%}
  </div>
  <main>
    {%- block main -%}
    {%- endblock %}
  </main>
  {%- block scripts -%}
    <script src="{{ url_for('static', filename='script/base.js') }}"></script>
  {%- endblock -%}
  {%- endblock -%}
</body>
</html>

poll/templates/create_poll.html
{% extends "base.html" %}
{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='style/create_poll.css') }}">
{% endblock %}
{% block title %}
    Create poll
{% endblock %}
{% block body %}
<form action="{{ url_for('poll.create_poll') }}" method="post" novalidate>
    {{ form.csrf_token }}
    <div>
        {{ form.title.label }} <br>
        {{ form.title }}
        {% if form.title.errors %}
            <span class="error-message">{{ form.title.errors[0] }}</span>
        {% else %}
            <br>
        {% endif %}
    </div>
    <div>
        {{ form.answer_options.label }} <br>
        {{ form.answer_options }}
        {% if form.answer_options.errors %}
            <span class="error-message">{{ form.answer_options.errors[0] }}</span>
        {% endif %}
    </div>
    <div>
        {{ form.multiple_choices }}
        {{ form.multiple_choices.label }} <br>
    </div>
    {{ form.submit }}
</form>
<script src="{{ url_for('static', filename='javascript/poll.js') }}"></script>
{% endblock %}

poll/templates/index.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main page</title>
</head>
<body>
    {% if current_user.is_authenticated %}
        <a href="/logout">Log out</a>
        <h1>Welcome {{ current_user['username'] }}</h1>
    {% endif %}

    <form action="{{ url_for('poll.poll') }}" method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <label for="question">Question:</label>
        <input type="text" name="question">
        <br>
        Answer options: <br>
        <ul id="answer_options">
            <li><input type="text" name="answer"></li>
            <li><input type="text" name="answer"></li>
            <li><input type="text" name="answer"></li>
        </ul>
        <button type="submit">Create poll</button>
    </form>
    <script src="{{ url_for('static', filename='javascript/poll.js') }}"></script>
</body>
</html>

poll/templates/main.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main</title>
</head>
<body>
    <h1>Welcome {{ current_user['username'] }}</h1>
</body>
</html>

poll/templates/poll.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ question }}</h1>
    <form action="{{ url_for('poll.poll') }}/{{ poll_id }}" method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <ul>
        {% for answer in answers %}
            <li>
                <input type="radio" name="choice" value="{{ answer['id'] }}"> {{ answer['text'] }} {{ answer['count'] }}
            </li>
        {% endfor %}
        </ul>
        <button>Vote</button>
    </form>
</body>
</html>

poll/templates/test.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
    {%- for fruit in fruits %}
        <li>{{ fruit }}</li>
    {%- endfor %}
    </ul>
</body>
</html>

poll/templates/vmi.j2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
    {% for answer in answers %}
        <li>{{ answer }}</li>
    {% endfor %}
    </ul>
</body>
</html>